# Generated by Django 3.2.6 on 2021-08-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duriation', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('trainer_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='enquqry_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
                ('start_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('total_fee', models.IntegerField()),
                ('joining_date', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_one.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=300)),
                ('class_fee', models.IntegerField()),
                ('joining_date', models.IntegerField()),
                ('parent_phno', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_one.enquqry_form')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_one.enquqry_form'),
        ),
    ]
